### ISSUE TITLE
`IBM Semeru Runtime Open Edition` missing

### ISSUE THREAD

**Issue by MPV** [joschi/java-metadata#46]
Hi,
Since the recent week, `IBM Semeru Runtime Open Edition` seems to have disappeared from this repo.

I see there was an attempt to add `IBM Semeru Runtime Certified Edition` in:
- https://github.com/joschi/java-metadata/commit/2b1e19bf1600a301e48c20964cdb1136e0d01ab3#diff-239420184e0c5383074f3d932f153af9d87b4fa434959a4514b81d5bcef568c5

...did the `Open Edition` by chance accidentally get dropped with this change adding `Certified Edition`?

**Comment by joschi** [comment]
Thanks for reporting this!

The data for IBM Semeru Runtime Open Edition was indeed "hidden" by adding support for the certified edition.

While the individual data was still available, the aggregated files such as https://joschi.github.io/java-metadata/metadata/vendor/semeru/all.json were missing them due to a bug in the provider scripts and how these aggregated files are created.

These commits should fix the issue:
- d0972ff8e54cae78c0a8c7028722e1107cb83ba6
- f607f3d3e5b5d87a518845158b6cdbe15da23c31
